export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirts",
      category: "shirts",
      image: "/images/d1.jpg",
      price: "600",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Fit Shirts",
      category: "shirts",
      image: "/images/d1.jpg",
      price: "800",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Slim Shirts",
      category: "pants",
      image: "/images/d1.jpg",
      price: "1200",
      brand: "Nike",
      rating: 3.2,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Slim Shirts",
      category: "pants",
      image: "/images/d1.jpg",
      price: "1200",
      brand: "Nike",
      rating: 3.2,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Slim Shirts",
      category: "pants",
      image: "/images/d1.jpg",
      price: "1200",
      brand: "Nike",
      rating: 3.2,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Slim Shirts",
      category: "pants",
      image: "/images/d1.jpg",
      price: "1200",
      brand: "Nike",
      rating: 3.2,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
